// <auto-generated />
using HockeyPlayoffs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HockeyPlayoffs.Migrations
{
    [DbContext(typeof(HockeyContext))]
    [Migration("20190423185920_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HockeyPlayoffs.Data.PlayoffPossibility", b =>
                {
                    b.Property<int>("PlayoffPossibilityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Atlantic1Games");

                    b.Property<string>("Atlantic1Winner");

                    b.Property<int>("Atlantic2Games");

                    b.Property<string>("Atlantic2Winner");

                    b.Property<int>("AtlanticGames");

                    b.Property<string>("AtlanticWinner");

                    b.Property<int>("Central1Games");

                    b.Property<string>("Central1Winner");

                    b.Property<int>("Central2Games");

                    b.Property<string>("Central2Winner");

                    b.Property<int>("CentralGames");

                    b.Property<string>("CentralWinner");

                    b.Property<int>("ChampionshipsGames");

                    b.Property<string>("ChampionshipsWinner");

                    b.Property<int>("EasternGames");

                    b.Property<string>("EasternWinner");

                    b.Property<int>("Metro1Games");

                    b.Property<string>("Metro1Winner");

                    b.Property<int>("Metro2Games");

                    b.Property<string>("Metro2Winner");

                    b.Property<int>("MetroGames");

                    b.Property<string>("MetroWinner");

                    b.Property<int>("Pacific1Games");

                    b.Property<string>("Pacific1Winner");

                    b.Property<int>("Pacific2Games");

                    b.Property<string>("Pacific2Winner");

                    b.Property<int>("PacificGames");

                    b.Property<string>("PacificWinner");

                    b.Property<int>("WesternGames");

                    b.Property<string>("WesternWinner");

                    b.HasKey("PlayoffPossibilityId");

                    b.ToTable("PlayoffPossibilities");
                });
#pragma warning restore 612, 618
        }
    }
}
